const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),dist=path.join(root,'dist');
const crypto=require('crypto'),presentation=JSON.parse(fs.readFileSync(path.join(root,'assets/presentation-v11.json'),'utf8'));
if(presentation.presentationRevision!=='v14'||presentation.geometryRevision!=='v09-r8'||presentation.experienceRevision!=='v11'||presentation.images.length!==8||presentation.plans.length!==3||presentation.downloads.length!==11||presentation.reviewMaps.length!==3)throw Error('Incomplete v14/r8 presentation');
for(const item of [...presentation.images,...presentation.plans,...presentation.downloads,...presentation.reviewMaps])if(!item.path.includes('-v14'))throw Error('Stale presentation path: '+item.path);
const imageIds=['showroom-arrival','showroom-smart','showroom-handover','showroom-overview','exterior-aerial','exterior-street','workshop-overview','workshop-smart-bays'];
assert.deepEqual(presentation.images.map(q=>q.id).sort(),imageIds.slice().sort(),'Eight unique v14 artist views required');
for(const q of presentation.images){assert.equal(q.acceptanceStatus,'accepted-by-root',q.id+' not explicitly accepted');assert.equal(q.geometryRevision,'v09-r8',q.id+' stale geometry review');assert.equal(q.width,1672);assert.equal(q.height,941);assert.match(q.generatedMasterSha256,/^[a-f0-9]{64}$/);assert.match(q.sourceRevision,/^v\d+(?:-r\d+)?$/);assert.equal(q.retentionStatus,q.sourceRevision==='v14'?'new-v14-artwork':'retained-after-current-geometry-review');if(q.sourceRevision!=='v14')assert(q.reviewNotes?.some(n=>typeof n==='string'&&n.trim()),q.id+' retained review notes required');const copies=presentation.downloads.filter(x=>x.id===q.id);assert.equal(copies.length,1,q.id+' unique native download');const native=copies[0];assert.equal(native.width,1672);assert.equal(native.height,941);assert.equal(native.nativeResolution,true);assert.equal(native.upscaled,false);assert.equal(native.geometryRevision,'v09-r8');assert.equal(native.sourceRevision,q.sourceRevision);assert.equal(native.retentionStatus,q.retentionStatus);assert.equal(native.generatedMasterSha256,q.generatedMasterSha256);}
for(const item of [...presentation.images,...presentation.plans,...presentation.downloads,...presentation.reviewMaps,presentation.favicon]){const bytes=fs.readFileSync(path.join(root,item.path));if(crypto.createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw Error('Presentation asset mismatch: '+item.path);}
for(const file of ['scene.js','experience.js','smart.js','mercedes-vehicles.js','smart-brand.js','building-annexes.js','workshop-interior.js','site.js','shrine.js','exterior-design.js','exterior-massing.js','review-guide.js','layout.js','feedback.js','feedback-config.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'layout.js'),'utf8'),context);const d=context.window.BC_LAYOUT;
if(d.revision!=='v09'||d.iteration!=='r8'||d.designRevision!=='v14'||d.states.length!==3||d.defaultState!=='handover'||d.site.revision!=='v09'||d.feedbackPolicy.submissionEnabled!==true||d.exterior.revision!=='v09')throw Error('Wrong revision/default/site/feedback policy');
const owner=JSON.parse(fs.readFileSync(path.join(root,'assets/owner-review-v12.json'),'utf8')),annexes=JSON.parse(fs.readFileSync(path.join(root,'assets/building-annexes.json'),'utf8')),profile=owner.module3BBackdrop,plain=q=>JSON.parse(JSON.stringify(q)),near=(a,b,n)=>assert(Math.abs(a-b)<1e-8,n);
assert.equal(profile.shape,'rounded-trapezoid-elevation');for(const [k,v]of Object.entries({bottomWidth:5.3,topWidth:4.9,height:2.5,bottomHeight:.06,thickness:.14,topCornerTrim:.3,bottomCornerTrim:.18}))near(profile[k],v,'Module3B '+k);assert.equal(profile.supplierGeometryVerified,false);
for(const s of d.states){const walls=s.furniture.filter(q=>q.type==='background-wall');assert.equal(walls.length,1);assert.deepEqual(plain(walls[0].elevationProfile),profile);assert.equal(walls[0].shape,profile.shape);}
const cover=d.site.annexes.workshop.rearCanopy,rear=d.site.workshopStudy.ownerLayout.rearParking;assert.deepEqual(plain(cover),annexes.workshop.rearCanopy);assert.equal(cover.roofScope,'full-rear-workshop-elevation');near(cover.xMin,2.02);near(cover.xMax,40);near(cover.xMax-cover.xMin,37.98);assert.equal(cover.render,true);assert.equal(rear.bays.length,10);assert.deepEqual(plain(rear.bankBounds),[15,43,40,48]);assert.deepEqual(plain(cover.coveredParkingBounds),plain(rear.bankBounds));assert.deepEqual(plain(cover.supportXs),[2.5,10,17.5,25,32.5,40]);for(let i=1;i<cover.supportXs.length;i++)near(cover.supportXs[i]-cover.supportXs[i-1],rear.width*3,'Three-bay support rhythm');assert.equal(cover.supportGrid.baysPerSpan,3);near(cover.supportGrid.nominalSpacing,7.5);assert.equal(cover.structuralApproval,false);assert.equal(d.site.exteriorParking.revision,'owner-v14-r8');
const equipment=d.site.workshopStudy.ownerLayout.equipment;
if(equipment.ownerExisting.length!==10||equipment.ownerExisting.filter(q=>q.kind==='two-post').length!==8||equipment.ownerExisting.filter(q=>q.kind==='four-post').length!==2||equipment.proposedAdditional.length!==0)throw Error('Wrong owner-confirmed workshop equipment inventory');
for(const s of d.states){if(s.cars.filter(c=>c.brand==='MB').length!==(s.mode==='handover'?6:5)||s.cars.filter(c=>c.brand==='smart').length!==1||s.module.type!=='Module 3B'||s.module.quantity!==1||s.furniture.some(q=>q.id==='ST')||s.people.length<8)throw Error('Wrong design state');}
fs.mkdirSync(dist,{recursive:true});fs.writeFileSync(path.join(root,'assets/geometry-register.json'),JSON.stringify(require('./export-geometry.cjs')(d),null,2)+'\n');
for(const name of ['index.html','viewer.css','experience.css','experience.js','scene.js','smart.js','mercedes-vehicles.js','smart-brand.js','building-annexes.js','workshop-interior.js','site.js','shrine.js','exterior-design.js','exterior-massing.js','review-guide.js','layout.js','feedback.js','feedback-config.js','assets','vendor','renders','versions'])fs.cpSync(path.join(root,name),path.join(dist,name),{recursive:true});
fs.writeFileSync(path.join(dist,'.nojekyll'),'');console.log('Static build complete: v14 presentation, v09-r8 owner review; v11 pinned-comment contract and archived designs preserved.');

require('./build-application-details.cjs')();
