const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),dist=path.join(root,'dist');
const crypto=require('crypto'),presentation=JSON.parse(fs.readFileSync(path.join(root,'assets/presentation-v11.json'),'utf8'));
if(presentation.presentationRevision!=='v12'||presentation.geometryRevision!=='v09-r6'||presentation.experienceRevision!=='v11'||presentation.images.length!==8||presentation.plans.length!==3||presentation.downloads.length!==11||presentation.reviewMaps.length!==3)throw Error('Incomplete v12/r6 presentation');
for(const item of [...presentation.images,...presentation.plans,...presentation.downloads,...presentation.reviewMaps])if(!item.path.includes('-v12'))throw Error('Stale presentation path: '+item.path);
for(const item of [...presentation.images,...presentation.plans,...presentation.downloads,...presentation.reviewMaps,presentation.favicon]){const bytes=fs.readFileSync(path.join(root,item.path));if(crypto.createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw Error('Presentation asset mismatch: '+item.path);}
for(const file of ['scene.js','experience.js','smart.js','mercedes-vehicles.js','smart-brand.js','building-annexes.js','workshop-interior.js','site.js','shrine.js','exterior-design.js','exterior-massing.js','review-guide.js','layout.js','feedback.js','feedback-config.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'layout.js'),'utf8'),context);const d=context.window.BC_LAYOUT;
if(d.revision!=='v09'||d.iteration!=='r6'||d.designRevision!=='v12'||d.states.length!==3||d.defaultState!=='handover'||d.site.revision!=='v09'||d.feedbackPolicy.submissionEnabled!==true||d.exterior.revision!=='v09')throw Error('Wrong revision/default/site/feedback policy');
const equipment=d.site.workshopStudy.ownerLayout.equipment;
if(equipment.ownerExisting.length!==10||equipment.ownerExisting.filter(q=>q.kind==='two-post').length!==8||equipment.ownerExisting.filter(q=>q.kind==='four-post').length!==2||equipment.proposedAdditional.length!==0)throw Error('Wrong owner-confirmed workshop equipment inventory');
for(const s of d.states){if(s.cars.filter(c=>c.brand==='MB').length!==(s.mode==='handover'?6:5)||s.cars.filter(c=>c.brand==='smart').length!==1||s.module.type!=='Module 3B'||s.module.quantity!==1||s.furniture.some(q=>q.id==='ST')||s.people.length<8)throw Error('Wrong design state');}
fs.mkdirSync(dist,{recursive:true});fs.writeFileSync(path.join(root,'assets/geometry-register.json'),JSON.stringify(require('./export-geometry.cjs')(d),null,2)+'\n');
for(const name of ['index.html','viewer.css','experience.css','experience.js','scene.js','smart.js','mercedes-vehicles.js','smart-brand.js','building-annexes.js','workshop-interior.js','site.js','shrine.js','exterior-design.js','exterior-massing.js','review-guide.js','layout.js','feedback.js','feedback-config.js','assets','vendor','renders','versions'])fs.cpSync(path.join(root,name),path.join(dist,name),{recursive:true});
fs.writeFileSync(path.join(dist,'.nojekyll'),'');console.log('Static build complete: v12 presentation, v09-r6 owner review; v11 pinned-comment contract and archived designs preserved.');
