const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p)),ctx={window:{}},tests=[];
function test(name,fn){fn();tests.push(name);}
function load(file){const c={window:{}};vm.runInNewContext(read(file).toString(),c);return JSON.parse(JSON.stringify(c.window.BC_LAYOUT));}
const d=load('layout.js'),old=load('versions/v07/layout.js');
test('v08 adds separate site; entire v07 interior states unchanged',()=>{assert.equal(d.revision,'v08');for(const k of ['states','building','smartVehicle'])assert.deepStrictEqual(d[k],old[k],k);assert.equal(d.site.revision,'v08');});
test('v07 primary source bytes and dependencies frozen at release',()=>{for(const p of ['index.html','viewer.css','scene.js','smart.js','review-guide.js','layout.js','feedback.js','feedback-config.js','assets/geometry-register.json','assets/smart-review-matrix.json','vendor/three.min.js','vendor/Reflector.source.js'])assert(read('versions/v07/'+p).equals(cp.execFileSync('git',['show','fbf02c0e1649af646ab97480fdadb14e489c2bd7:'+p],{cwd:root,maxBuffer:10000000})),p);});
test('Three new camera presets are distinct from six preserved views',()=>{const html=read('index.html').toString(),views=[...html.matchAll(/data-view="([^"]+)"/g)].map(m=>m[1]);assert.equal(views.length,9);assert.equal(new Set(views).size,9);for(const v of ['site','frontage','siteplan','interior','smart','handover','service','overview','plan'])assert(views.includes(v));assert(read('scene.js').toString().includes('if(!Object.hasOwn(presets,v))return false'));});
test('Site privacy/confidence and corrected printed dimension endpoints explicit',()=>{assert.equal(d.site.front.setbackFromPlinth.value,7.2);assert.equal(d.site.front.apronEdgeY.value,-8.4);assert.equal(d.site.front.gate.width,8);assert.match(d.site.front.setbackFromPlinth.status,/not grid H/);assert.match(d.site.status,/NOT cadastral/);assert.match(d.site.sidewalk.status,/NOT A01 printed 3.10/);assert.match(d.site.rearClip.status,/not rear boundary/);assert.match(d.site.levels.warning,/unconfirmed/);assert.equal(d.site.alternativeA04.frontStairWidthReading,10.4);});
test('Public register exactly carries current site controls',()=>assert.deepStrictEqual(JSON.parse(read('assets/geometry-register.json')).site,d.site));
test('Owner-enabled feedback fails closed until all revision capabilities pass; pins remain interior-only',()=>{vm.runInNewContext(read('feedback-config.js').toString(),ctx);assert.match(ctx.window.BC_FEEDBACK_CONFIG.endpoint,/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/);assert.equal(ctx.window.BC_FEEDBACK_CONFIG.submissionEnabled,true);assert.equal(d.feedbackPolicy.submissionEnabled,true);const f=read('feedback.js').toString();for(const s of ['if(submissionEnabled&&endpointConfigured)','!submissionEnabled || !validEndpoint','h.schema===1','Array.isArray(h.revisions)','Array.isArray(h.modesByRevision?.[revision])','Array.isArray(h.viewsByRevision?.[revision])',"query.get(k).trim()!==''","x>=0 && x<=40 && y>=0 && y<=16"])assert(f.includes(s),s);});
test('New site assets are wired in dependency order and copied to dist',()=>{const html=read('index.html').toString();for(const p of ['site.js','exterior-massing.js']){assert(html.indexOf('src="./'+p+'"')<html.indexOf('src="./scene.js"'));assert(read(p).equals(read('dist/'+p)));}});
test('Root v07 permalinks route to frozen archive',()=>assert(read('index.html').toString().includes("['v04','v06','v07'].includes(r)")));
test('v08 generator is deterministic',()=>{const before=read('layout.js');cp.execFileSync(process.execPath,['scripts/revise-layout-v08.cjs'],{cwd:root});assert(before.equals(read('layout.js')));});
test('Smart mesh remains exactly v07; compliance source intent preserved',()=>{assert(read('smart.js').equals(read('versions/v07/smart.js')));assert(read('assets/smart-review-matrix.json').equals(read('versions/v07/assets/smart-review-matrix.json')));});
console.log(JSON.stringify({status:'PASS',revision:d.revision,tests:tests.length,names:tests,layoutSHA256:crypto.createHash('sha256').update(read('layout.js')).digest('hex'),limits:'Deterministic static checks, not browser/device/survey/engineering approval'},null,2));
