const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p)),load=p=>{const c={window:{}};vm.runInNewContext(read(p).toString(),c);return JSON.parse(JSON.stringify(c.window.BC_LAYOUT));};
const d=load('layout.js'),old=load('versions/v08/layout.js'),tests=[];function test(n,f){f();tests.push(n);}
test('Revision, frozen interior and vehicle selection retained',()=>{assert.equal(d.revision,'v09');for(const k of ['states','building','smartVehicle'])assert.deepEqual(d[k],old[k]);assert(read('smart.js').equals(read('versions/v08/smart.js')));});
test('Published v08 archive unchanged',()=>{for(const f of ['index.html','viewer.css','scene.js','smart.js','site.js','exterior-massing.js','review-guide.js','layout.js','feedback.js','feedback-config.js','assets/site-context.json'])assert(read('versions/v08/'+f).equals(cp.execFileSync('git',['show','506b3a4ecb2a580f4a7d2f050d3fa8aa6b63fcb3:'+f],{cwd:root,maxBuffer:10000000})),f);});
test('Existing 3 MB, 2 Thai flags, shrine, pylon and bounded curve',()=>{const a=d.site.existingInventory;assert.equal(a.filter(q=>q.type==='mercedes-banner').length,3);assert.equal(a.filter(q=>q.type==='thai-national-flag').length,2);assert.equal(a.filter(q=>q.id==='SHRINE').length,1);assert.equal(a.filter(q=>q.id==='MB-PYLON').length,1);assert.equal(d.site.corner.filletRadius,6);assert.equal(d.site.east.openingEnabled,false);assert.equal(d.site.front.gate.legacyPrintedWidth,8);assert.equal(d.site.front.gate.width,18.5);assert.equal(d.site.sources.find(s=>s.id==='N07').date,'2023-10');});
test('Manual envelopes; exactly three proposed bays and no duplicate facade',()=>{const p=d.exterior;assert.equal(p.pylon.height,4.515);assert.equal(p.pylon.width,1.466);assert.equal(p.flag.height,4.5);assert.equal(p.flag.width,1.2);assert.equal(p.parking.length,3);p.parking.forEach(b=>{assert.equal(b.width,2.8);assert.equal(b.length,5.5);});assert.equal(p.careLogo.width,2.07);assert.match(p.status,/NOT approved/);});
test('Owner R2 orientation and direction waiver remain explicit',()=>{for(const q of [d.site.markers.pylonData,d.site.markers.directionData])assert.equal(q.rotationRadians,Math.PI/2);assert.equal(d.exterior.directionBoard.enabled,false);const m=JSON.parse(read('assets/smart-review-matrix.json'));assert.equal(m.rows.find(r=>r.id==='4').status,'waiver_pending');assert.equal(m.rows.find(r=>r.id==='4').standard,'required_flexible');});
test('Meeting outside Sales and attached workshop are registered separately',()=>{const a=d.site.annexes;assert.equal(a.meeting.fitEnvelope.xMax,0);assert.equal(a.workshop.footprint.yMin,16);assert.equal(a.workshop.attachment.y,16);assert.equal(a.workshop.awning.xMin,a.workshop.footprint.xMax);assert.equal(d.site.rearClip.y,50);assert.equal(d.site.edgeControlPoints.at(-1)[1],30);assert.equal(d.exterior.serviceCanopy.replacedBy,'site.annexes.workshop.awning');});
test('Logo artwork uses all seven source path strings without generic-font substitution',()=>{const paths=JSON.parse(read('assets/smart-brand/logo-paths.json'));assert.equal(paths.paths.length,7);for(const p of paths.paths){const source=read('assets/smart-brand/'+(p.component==='symbol'?'smart-symbol-source.svg':'smart-wordmark-white-source.svg')).toString();assert(source.includes(p.d),'Original path absent from official source');}assert(read('smart-brand.js').toString().includes(JSON.stringify(paths)));for(const f of ['smart-brand.js','building-annexes.js','assets/building-annexes.json','assets/smart-brand/smart-stacked-white-pylon-study.svg'])assert(read(f).equals(read('dist/'+f)),f);});
test('Archived routes and ten current scheme/feedback views',()=>{const html=read('index.html').toString(),fb=read('feedback.js').toString();assert(html.includes("['v04','v06','v07','v08'].includes(r)"));assert.equal((html.match(/data-view=/g)||[]).length,10);assert(html.includes('id="exterior-scheme"'));assert(fb.includes('exteriorScheme:currentExterior()'));assert(fb.includes('Array.isArray(h.exteriorSchemesByRevision?.[revision])'));});
test('R3 drawing controls, continuous tower and workshop study are canonical',()=>{const s=d.site,a=s.annexes;assert.equal(d.iteration,'r3');assert.equal(s.legacyDrawingControls.letterGrid.A,42);assert.equal(s.legacyDrawingControls.numericGrid['3'],2.02);assert.equal(a.workshop.footprint.yMax,42);assert.equal(a.workshop.floorLevel,-.6);assert.equal(a.workshop.awning.xMax,49.2);assert.deepEqual(s.upperBuilding.masterCorner,a.meeting.masterTowerCorner);assert.equal(s.upperBuilding.masterCorner.frontY,-1.9);assert.equal(s.workshopStudy.smartBays.length,2);assert.deepEqual(s.workshopStudy,d.exterior.workshopStudy);for(const f of s.markers.flagData)assert.equal(f.xy[1],-7.75);assert.equal(s.markers.directionData.faces.reverseExit[0][0],'Exit');for(const f of ['workshop-interior.js','assets/legacy-drawing-controls.json','assets/workshop-study.json'])assert(read(f).equals(read('dist/'+f)),f);});
test('Current model assets present in exact dist bytes',()=>{for(const f of ['index.html','scene.js','smart.js','site.js','shrine.js','exterior-design.js','exterior-massing.js','feedback.js','layout.js','assets/exterior-proposal.json','assets/site-context.json','assets/smart-review-matrix.json'])assert(read(f).equals(read('dist/'+f)),f);});
test('Deterministic revision generator',()=>{const before=read('layout.js');cp.execFileSync(process.execPath,['scripts/revise-layout-v09.cjs'],{cwd:root});assert(before.equals(read('layout.js')));});
console.log(JSON.stringify({status:'PASS',revision:d.revision,tests:tests.length,names:tests,limitations:'Static/CPU checks only; no survey, GPU, device, engineering or compliance certification'},null,2));
