const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p)),ctx={window:{}};vm.runInNewContext(read('layout.js').toString(),ctx);const d=ctx.window.BC_LAYOUT,tests=[];
function test(name,fn){fn();tests.push(name);}
test('Confirmed Y / assumed X remain separate',()=>{assert.deepStrictEqual(JSON.parse(JSON.stringify(d.building.grids.Y)),{H:0,G:2.5,F:8,E:16});assert.match(d.building.grids.XStatus,/assumed/);});
test('Owner-adopted logo, reuse charger and all states',()=>{for(const s of d.states){assert.equal(s.cars.filter(c=>c.brand==='smart').length,1);assert.equal(s.cars.filter(c=>c.brand==='MB').length,s.mode==='handover'?6:5);assert.equal(s.module.quantity,1);assert.equal(s.module.type,'Module 3B');assert(!s.furniture.some(q=>q.id==='CH'||q.id==='ST'));const q=s.furniture.find(q=>q.id==='SHARED-EV');assert.equal(q.cx,32.85);assert(q.retained);const l=s.furniture.find(q=>q.id==='SMART-WINDOW-LOGO');assert.equal(l.cx,35.97);assert.equal(l.cy,2.73);assert.match(l.installation,/Type 4/);assert.equal(s.furniture.find(q=>q.id==='VM').cx,24.45);}});
test('C-return stair and curved Manager data',()=>{assert.equal(d.building.stair.landings.length,2);assert.equal(d.building.stair.renderOnly.totalRise,3.56);assert(d.building.manager.polygon.length>10);});
test('All35 requirement IDs unique',()=>{const m=JSON.parse(read('assets/smart-review-matrix.json'));assert.equal(m.rows.length,35);assert.equal(new Set(m.rows.map(r=>r.id)).size,35);assert(!/1oh82EyW|eaefd951|c6569eb1|0dcb7cd3/.test(JSON.stringify(m)));});
test('Frozen v06 primary assets match released base',()=>{for(const p of ['index.html','viewer.css','scene.js','layout.js','feedback.js','feedback-config.js','vendor/three.min.js','vendor/Reflector.source.js'])assert(read('versions/v06/'+p).equals(cp.execFileSync('git',['show','a9ebd3979440fd6971bb6f9612c6c6c26483a2b4:'+p],{cwd:root,maxBuffer:10000000})),p);});
test('Frozen v04 remains unchanged',()=>assert.equal(cp.execFileSync('git',['diff','--name-only','a9ebd3979440fd6971bb6f9612c6c6c26483a2b4','--','versions/v04'],{cwd:root}).toString(),''));
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);}
test('Every static local HTML dependency resolves in dist',()=>{for(const p of walk(path.join(root,'dist')).filter(p=>p.endsWith('.html'))){const s=fs.readFileSync(p,'utf8');for(const m of s.matchAll(/(?:src|href)="([^"]+)"/g)){const v=m[1];if(/^(https?:|data:|#)/.test(v))continue;let f=path.resolve(path.dirname(p),v.split(/[?#]/)[0]);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');assert(fs.existsSync(f),p+': '+v);}}});
test('No originals or backend in public build',()=>{for(const p of walk(path.join(root,'dist'))){assert(!/\.(pdf|gs|webp)$/i.test(p),p);assert(!/client.*log|smart-assets\/images/i.test(p),p);}});
test('Root submit preserves fail-closed capability validation',()=>{const s=read('feedback.js').toString();assert.match(s,/let validEndpoint=false/);assert(s.includes('Array.isArray(h.revisions)&&h.revisions.includes(revision)'));assert(s.includes('modes.every(m=>h.modesByRevision[revision].includes(m))'));assert(s.includes('views.every(v=>h.viewsByRevision[revision].includes(v))'));});
test('Updated smart factory is wired for window logo',()=>{assert(read('scene.js').toString().includes("q.type==='window-logo'"));assert(read('smart.js').toString().includes('Schematic glass standoffs'));});
console.log(JSON.stringify({status:'PASS',tests:tests.length,names:tests,revision:d.revision,layoutSHA256:crypto.createHash('sha256').update(read('layout.js')).digest('hex'),limits:'Static/unit checks, not device/engineering/brand approval'},null,2));
